const { PrismaPg } = require('@prisma/adapter-pg');
const { PrismaClient } = require('@prisma/client');

if (!process.env.DATABASE_URL) {
  throw new Error('DATABASE_URL is required to run seed');
}

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const teaDescriptions = new Map([
  ['heirloom-silver-needle', 'To biała herbata typu Fuding Yin Zhen, wytwarzana tradycyjnymi metodami z krzewów mających od 30 do 50 lat. Proces produkcji obejmuje więdnięcie na słońcu oraz wielodniowe leżakowanie, co nadaje naparowi wyjątkową gęstość i charakterystyczne orzechowe nuty. Herbata kończona jest delikatnym pieczeniem nad węglem drzewnym, co wzmacnia jej aromat i potencjał do starzenia.'],
  ['silver-needle', 'Wyjątkowo aromatyczna biała herbata, zbierana ręcznie tylko przez dwa dni w roku wyłącznie z młodych, puszystych pąków odmiany Da Ye Zhong. Proces powolnego więdnięcia na słońcu wydobywa z niej naturalną słodycz biszkoptu oraz nuty gardenii, kwiatu pomarańczy i owoców agrestu. Napar charakteryzuje się gęstą, niemal kremową teksturą, dzięki której często nazywana jest „szampanem wśród białych herbat".'],
  ['white-peony', 'To słodka i bogata herbata biała typu Fuding, powstała z mieszanki pąków i młodych liści z 50-letnich krzewów odmiany Da Bai. Jest suszona naturalnie na słońcu, co nadaje jej wyraźne nuty orzechowego nugatu, kwiatów orchidei oraz miodu łąkowego. Dzięki wysokiej jakości zbioru i tradycyjnej metodzie produkcji, herbata ta doskonale nadaje się do wieloletniego starzenia.'],
  ['moonlight-white', 'Wyjątkowa biała herbata pochodząca z regionu Jinggu w Yunnan, wytwarzana ze 150-letnich drzew gatunku Camellia Taliensis. Charakteryzuje się kremową, syropowatą teksturą oraz bogatym profilem aromatycznym z nutami miodu spadziowego, lilii i dojrzałego mango. Proces powolnego więdnięcia i suszenia wewnątrz pomieszczeń nadaje jej ciemniejszy kolor liści oraz większą słodycz, która z czasem nabiera jeszcze głębszego charakteru.'],
  ['wild-slumber', 'To niezwykła „dzika" biała herbata z krzewów odmiany Da Bai posadzonych w latach 70. w Fuding, które z czasem zdziczały. Charakteryzuje się intensywnym aromatem cukierków owocowych, grejpfruta i miodu, przełamanym nutami leśnymi i żywicznymi. W przeciwieństwie do klasycznych białych herbat, oferuje mocne, niemal euforyczne doznania i unikalną mineralność przypominającą herbaty typu oolong.'],
  ['simple-dreams-3', 'To unikalna mieszanka dwóch stylów herbaty białej typu Shou Mei z regionu Zhenghe, łącząca liście suszone na słońcu z wersją celowo poddaną mocniejszej oksydacji. Efektem jest bogaty, kremowy napar o aromacie konfitury truskawkowej, rabarbaru i miodu, który przywodzi na myśl klasyczny brytyjski podwieczorek. Herbata ta świetnie smakuje teraz, ale ze względu na swoją strukturę posiada również ogromny potencjał do dalszego starzenia.'],
  ['jade-star-9', 'To wyjątkowa, dojrzewająca przez 18 lat mieszanka białych herbat typu Shou Mei i Bai Mu Dan z regionu Fuding. Łączy w sobie głębokie, sfermentowane nuty ciemnych owoców i dżemu morelowego z kremowym aromatem ciasta drożdżowego oraz marcepana. Napar jest gęsty, syropowaty i oferuje niezwykle złożone doznania, określane przez twórców jako „pijana radość".'],
  ['lost-origin-white', 'To unikatowa biała herbata wytwarzana z pierwotnej, drobnolistnej odmiany Xiao Cai Cha z okolic góry Taimu, uważanej za przodka wszystkich herbat białych. Charakteryzuje się niezwykle złożonym profilem, łączącym kremowe nuty bitej śmietany i marcepanu z mineralnym akcentem mokrych kamieni oraz świeżością zielonego groszku. Herbata ta dojrzewała od 2021 roku, co nadało jej dodatkowej głębi, gładkości i słodyczy, która z każdym parzeniem staje się coraz bardziej intensywna.'],
  ['purple-bud', 'To rzadka herbata z prowincji Yunnan, zbierana z dzikich drzew odmiany Ye Sheng Dehongensis, naturalnie bogatych w antocyjany, które nadają liściom fioletowy odcień. Choć pochodzi z drzew typu Pu Erh, jej proces obróbki (suszenie na słońcu) zbliża ją do herbat białych, oferując unikalny profil z nutami sorbetu brzoskwiniowego, czarnego bzu i igieł sosny. Napar jest lekki, a odpowiednio parzony (w niższej temperaturze) staje się słodki i kwiatowy, unikając typowej dla dzikich odmian goryczki.'],
  ['wenzhou-gold', 'To słynna żółta herbata z regionu Pinyang w prowincji Zhejiang, znana z tradycyjnej obróbki „Men Huang", polegającej na wielokrotnym owijaniu liści w papier ryżowy w celu uzyskania delikatnej oksydacji. Charakteryzuje się intensywnie żółtym naparem oraz bogatym smakiem łączącym nuty prażonych orzechów laskowych, kukurydzy, słodu i owoców gwiezdnych (karamboli). Jest to herbata o pełnym body i relaksującym działaniu, która przez stulecia cieszyła się statusem herbaty imperialnej.'],
  ['amber-mountain', 'To rzadka i elegancka żółta herbata z regionu Huoshan w prowincji Anhui, wytwarzana pracochłonną metodą parowania i przykrywania liści, co eliminuje trawiasty posmak typowy dla zielonych herbat. Oferuje wyjątkowo gładki, słodki profil z nutami nugatu, krakersów sezamowych oraz świeżych jabłek i wiosennej łąki. Napar o barwie soku winogronowego działa oczyszczająco i uziemiająco, będąc doskonałym przykładem odrodzonego rzemiosła produkcji herbat żółtych.'],
  ['sovereign-bud', 'Wybitna żółta herbata z gór Mengding, wytwarzana ręcznie przez mistrza Li z ponad 50-letnich krzewów odmiany Qun Ti Zhong. Proces produkcji jest niezwykle pracochłonny i obejmuje wielokrotne smażenie na patelni oraz owijanie pąków w specjalny papier na 35 godzin, co nadaje jej unikalny, "cukierkowy" charakter. W smaku dominują bogate nuty słonego karmelu, czekolady słodowanej, nugatu oraz pieczonych orzechów, tworząc gęsty i niezwykle trwały napar o słodkim wykończeniu.'],
  ['diamond-peak', 'Elegancka i złożona żółta herbata z regionu Yueyang w prowincji Hunan, blisko spokrewniona ze słynną Junshan Yinzhen. Charakteryzuje się kremowym, lekko przyprawowym profilem z wyraźnymi nutami guawy, nasion słonecznika oraz świeżego górskiego powietrza. Proces wielodniowego „żółknięcia" liści nadaje naparowi wyjątkową gładkość i owocową kwasowość, czyniąc go doskonałą alternatywą dla najdroższych, limitowanych edycji herbat z tego regionu.'],
  ['legend-of-the-limelight', 'To wyjątkowy, autorski blend dojrzewających herbat PuErh typu Sheng (surowych), łączący 20-letnią herbatę z Yibang (rocznik 2005) oraz 16-letnią z Bulang (rocznik 2009). Herbata z Yibang, przechowywana w warunkach suchych, wnosi nuty suszonych owoców, miodu i antycznych bibliotek, podczas gdy Bulang z „mokrego" składowania dodaje charakterystycznej wilgotnej, leśnej głębi z akcentami kamfory i orzechów. Całość tworzy niezwykle złożony napar o gęstej teksturze i potężnym działaniu energetycznym (tzw. tea high).'],
  ['young-gushu-2025', 'To biała herbata typu Yue Guang Bai (Moonlight White) z regionu Jinggu w Yunnan, wytwarzana z liści wiekowych drzew gatunku Camellia Taliensis. Charakteryzuje się niezwykle gęstą, syropowatą teksturą oraz bogatym profilem aromatycznym z nutami miodu spadziowego, białych kwiatów i dojrzałego mango. Dzięki wysokiej jakości surowca z drzew Gushu, herbata ta oferuje potężne doznania cielesne oraz doskonały potencjał do wieloletniego dojrzewania.'],
  ['90s-enigma-sheng', 'To niezwykle rzadki i tajemniczy Raw PuErh z lat 90., pochodzący z prywatnych kolekcji w Hongkongu i Tajwanie. Charakteryzuje się głębokim, „antycznym" profilem z nutami starego drewna, kadzidła, suszonych daktyli oraz charakterystyczną dla długiego leżakowania kamforą. Napar oferuje potężne, uziemiające działanie (Cha Qi) oraz gęstą, jedwabistą teksturę, która pozostaje na podniebieniu długo po degustacji.'],
  ['glam-countess', 'To luksusowa herbata biała typu Bai Mu Dan (White Peony) z regionu Fuding, zbierana z 50-letnich krzewów odmiany Da Bai. Wyróżnia się niezwykłą elegancją i czystością smaku, oferując bogaty bukiet aromatów - od kwiatów orchidei i gardenii, po słodkie nuty miodu i białych winogron. Napar ma jedwabistą teksturę i głęboką strukturę, która sprawia, że herbata ta wybitnie nadaje się do wieloletniego starzenia, z czasem zyskując jeszcze większą szlachetność.'],
  ['midnight-oracle', 'To głęboka i esencjonalna herbata typu Shu PuErh (dark tea) z regionu Menghai, stworzona z liści zebranych wiosną 2021 roku. Charakteryzuje się niezwykle gładką, niemal "oleistą" teksturą oraz bogatym profilem aromatycznym, w którym dominują nuty ciemnej czekolady, palonego karmelu i dojrzałych owoców leśnych. Dzięki starannemu procesowi fermentacji (wo dui), herbata ta jest pozbawiona ziemistości, oferując w zamian czysty, kojący smak z delikatnym mineralnym wykończeniem.'],
  ['bliss-beholder', 'To wyjątkowa biała herbata typu Bai Mu Dan (Biała Piwonia) z regionu Fuding, która została poddana procesowi lekkiego pieczenia nad węglem drzewnym. Dzięki temu zabiegowi klasyczne kwiatowe nuty zostały wzbogacone o głębokie aromaty prażonych orzechów, ciepłego biszkoptu i miodu gryczanego. Napar jest niezwykle gęsty i kojący, łącząc w sobie świeżość białej herbaty z bogactwem i "ciałem" charakterystycznym dla herbat poddawanych obróbce termicznej.'],
  ['off-the-apps', 'To wyjątkowa, dojrzewająca przez 15 lat (od 2009 roku) biała herbata typu Shou Mei z Fuding, która zachwyca swoją głębią i "antykowym" charakterem. Napar łączy w sobie nuty suszonych daktyli, miodu spadziowego i starego drewna, oferując niezwykle gładką, niemal oleistą teksturę. Herbata ta jest idealnym przykładem tego, jak czas szlachetnie zmienia białą herbatę, nadając jej kojące, uziemiające działanie i bogaty, deserowy profil.'],
  ['sweet-treat-envoy', 'To wyjątkowa biała herbata typu Shou Mei z 2021 roku, która została sprasowana w formę 7-gramowych kostek ("mini cakes") dla wygody parzenia. Charakteryzuje się niezwykle słodkim, miodowym profilem z wyraźnymi nutami suszonych owoców, herbatników i kwiatów łąkowych. Dzięki wysokiej jakości liści z regionu Fuding, herbata ta oferuje gęstą strukturę naparu oraz doskonały potencjał do dalszego dojrzewania, stając się z czasem jeszcze gładszą i bardziej deserową.'],
  ['juice-journo', 'To niezwykle soczysta i owocowa biała herbata typu Yue Guang Bai (Moonlight White) z regionu Jinggu w prowincji Yunnan, zebrana w 2024 roku. Wyróżnia się profilami smakowymi przypominającymi nektar z mango, liczi i białych brzoskwiń, przełamanymi delikatną kwiatową nutą lilii. Dzięki obróbce z liści wiekowych drzew, herbata posiada gęstą, syropowatą strukturę oraz długi, słodki posmak, który utrzymuje się przez wiele parzeń.'],
  ['dragon-pearl-jasmine', 'To najwyższej klasy zielona herbata z prowincji Fujian, ręcznie zwijana w formę niewielkich perełek, które rozwijają się podczas parzenia. Liście są naturalnie aromatyzowane świeżymi kwiatami jaśminu aż siedmiokrotnie, co nadaje naparowi intensywny, odurzający zapach i czysty, słodki smak bez cienia goryczy. Herbata ta zachwyca nie tylko eleganckim wyglądem, ale i niezwykle długim, kwiatowym posmakiem, który pozostaje na podniebieniu.'],
  ['cloud-lake', 'To wyjątkowa, rzemieślnicza zielona herbata z regionu Enshi w prowincji Hubei, wytwarzana z liści rosnących na wysokości powyżej 1000 m n.p.m. Charakteryzuje się niezwykle świeżym, "zielonym" profilem z dominującymi nutami słodkiego groszku cukrowego, młodych szparagów i świeżo skoszonej trawy. Napar jest lekki, maślanie gładki i posiada wyraźną słodycz, która sprawia, że jest to idealna herbata do codziennego celebrowania wiosennej świeżości.'],
  ['kabuse-saeakari', 'To japońska zielona herbata z kultywaru Saeakari, uprawiana w regionie Kirishima i poddawana procesowi zacieniania przed zbiorami (kabuse). Dzięki temu zabiegowi napar zyskuje intensywny kolor neonowej zieleni oraz głęboki profil umami z nutami słodkiego zielonego groszku, kremowych nerkowców i świeżych alg. Herbata ta łączy w sobie rześkość typową dla senchy z bogatą, aksamitną teksturą, oferując jednocześnie długi i niezwykle czysty posmak.'],
  ['monkey-picked', 'To najwyższej klasy oolong z Anxi, którego nazwa nawiązuje do legendarnej jakości herbat zbieranych dawniej z niedostępnych partii gór. Charakteryzuje się niezwykle intensywnym, kwiatowym aromatem orchidei i gardenii, połączonym z kremową teksturą i maślanym posmakiem. Napar jest czysty, jasny i bardzo trwały, oferując bogate doznania smakowe przez wiele kolejnych parzeń bez pojawiania się goryczy.'],
  ['tianshan-mist', 'To klasyczna chińska zielona herbata typu Mao Feng z gór Tianshan, zbierana wczesną wiosną, gdy pąki są najbardziej delikatne. Napar charakteryzuje się rześkim, roślinnym profilem z nutami słodkiej kukurydzy, kasztanów oraz delikatnym, kwiatowym wykończeniem. Dzięki tradycyjnej obróbce herbata ta jest wyjątkowo lekka i orzeźwiająca, oferując czysty smak górskiej mgły zamknięty w każdym parzeniu.'],
  ['jade-arrow-pre-qing-ming', 'To prestiżowa zielona herbata z kultywaru Bai Ye No. 1, który wiosną produkuje liście o bardzo niskiej zawartości chlorofilu, co nadaje im niemal biały kolor i wyjątkowy skład chemiczny. Dzięki ekstremalnie wysokiej zawartości aminokwasów (teaniny), napar posiada niespotykaną słodycz i intensywne, bulionowe umami z nutami szparagów i cytrusów. Herbata ta jest ceniona za swoją lekkość, jedwabistą strukturę oraz elegancki, "igiełkowy" kształt liści przypominający jadeitowe strzały.'],
  ['fur-peak-supreme', 'To wyjątkowa zielona herbata z regionu Huangshan, zbierana wczesną wiosną, gdy pąki pokryte są delikatnym, srebrzystym meszkiem (stąd nazwa „Futerzysty Szczyt"). Charakteryzuje się subtelnym, czystym profilem z nutami słodkich moreli, kasztanów oraz świeżych kwiatów magnolii. Napar jest lekki, jedwabisty i niezwykle orzeźwiający, stanowiąc wzorcowy przykład elegancji klasycznych chińskich herbat zielonych typu Mao Feng.'],
  ['amber-gaba-oolong', 'To wyjątkowy tajwański oolong poddany specjalnemu procesowi obróbki beztlenowej, który naturalnie zwiększa zawartość kwasu gamma-aminomasłowego (GABA), znanego z właściwości relaksujących. Herbata charakteryzuje się głębokim, bursztynowym kolorem naparu oraz bogatym profilem smakowym z nutami suszonych owoców, cynamonu, miodu i pieczonych jabłek. Jest to herbata o niezwykle gładkiej teksturze, która łączy w sobie prozdrowotne działanie z kojącym, deserowym charakterem.'],
  ['butterscotch-temple', 'To wyjątkowy tajwański oolong z odmiany Jin Xuan (Milk Oolong), poddany tradycyjnemu, wielogodzinnemu wypalaniu nad węglem drzewnym. Proces ten przekształca naturalną mleczność herbaty w głębokie, deserowe nuty przypieczonego karmelu, toffi oraz masła orzechowego. Napar jest niezwykle gęsty, kremowy i rozgrzewający, stanowiąc idealne połączenie klasycznej słodyczy z dymnym, rzemieślniczym charakterem.'],
  ['yunnan-beauty', 'To unikalny oolong z prowincji Yunnan, zainspirowany słynną tajwańską herbatą Oriental Beauty, powstały dzięki naturalnej interakcji liści z małymi owadami (skoczkami), co inicjuje proces tworzenia wyjątkowych aromatów. Charakteryzuje się bogatym, miodowo-owocowym profilem z wyraźnymi nutami dojrzałych brzoskwiń, róż i winogron Muscat. Napar jest aksamitny i gęsty, łącząc w sobie charakterystyczną dla Yunnanu głębię z egzotyczną, nektarową słodyczą.'],
  ['tiger-eye-gaba', 'To wyjątkowy, lekko oksydowany tajwański oolong, który dzięki specjalnemu procesowi obróbki beztlenowej zawiera bardzo wysoką dawkę relaksującego kwasu GABA. Wyróżnia się niezwykle czystym i jasnym profilem smakowym z nutami soczystych cytrusów, marakui oraz białych kwiatów, co jest rzadkością wśród zazwyczaj cięższych herbat typu GABA. Napar jest lekki, orzeźwiający i ma jedwabistą teksturę, oferując jednocześnie silne działanie kojące i poprawiające nastrój.'],
  ['duck-shit-oolong', 'Jeden z najbardziej znanych oolongów z gór Phoenix (Dan Cong), którego przewrotna nazwa miała dawniej chronić sekret unikalnego szczepu przed kradzieżą. Herbata ta słynie z oszałamiającego, naturalnie kwiatowego aromatu przypominającego gardenię, jaśmin i wiciokrzew, z wyraźną miodową słodyczą w tle. Napar jest niezwykle rześki, ma gęstą teksturę i pozostawia na podniebieniu długi, elegancki posmak, który przeczy jego nietypowej nazwie.'],
  ['alishan-creams', 'To klasyczny wysokogórski oolong z gór Ali Shan na Tajwanie, pochodzący z odmiany Jin Xuan, która słynie ze swojej naturalnej mleczności. Napar charakteryzuje się niezwykle maślaną, kremową teksturą oraz delikatnym aromatem wanilii, wiosennych kwiatów i świeżych ziół. Jest to herbata o czystym, słodkim profilu, która doskonale oddaje rześki charakter mglistych plantacji położonych na dużych wysokościach.'],
  ['lotus-peak-rou-gui', 'To klasyczna herbata skalna (Yancha) z gór Wuyi, pochodząca z jednego z najstarszych i najbardziej cenionych kultywarów w tym regionie. Charakteryzuje się gęstą, maślaną teksturą oraz bogatym profilem smakowym, w którym nuty pieczonych owoców i karmelu łączą się z wyraźną, mineralną bazą ("skalnym rymem"). Proces tradycyjnego wypalania nad węglem drzewnym nadaje naparowi głębię i kojący charakter, pozostawiając na podniebieniu długi, słodko-kremowy posmak.'],
  ['stone-milk', 'To klasyczna herbata skalna (Yancha) z gór Wuyi, pochodząca z jednego z najstarszych i najbardziej cenionych kultywarów w tym regionie. Charakteryzuje się gęstą, maślaną teksturą oraz bogatym profilem smakowym, w którym nuty pieczonych owoców i karmelu łączą się z wyraźną, mineralną bazą ("skalnym rymem"). Proces tradycyjnego wypalania nad węglem drzewnym nadaje naparowi głębię i kojący charakter, pozostawiając na podniebieniu długi, słodko-kremowy posmak.'],
  ['honey-duchess', 'To wyjątkowy tajwański oolong typu Oriental Beauty, który swoją unikalną słodycz zawdzięcza naturalnej reakcji krzewów na podgryzanie liści przez małe skoczki zielone. Proces ten inicjuje produkcję terpenów, nadając naparowi intensywne nuty miodu spadziowego, dżemu różanego oraz dojrzałych owoców egzotycznych. Herbata zachwyca gęstą, jedwabistą teksturą i głębokim aromatem, który z każdą kolejną sesją parzenia rozwija coraz to szlachetniejsze oblicze.'],
  ['royal-peach-orchid', 'To jeden z najbardziej cenionych oolongów typu Dan Cong z gór Phoenix, słynący z intensywnego, naturalnego aromatu miodu i dojrzałych brzoskwiń. Napar charakteryzuje się bogatą, kwiatową strukturą z nutami orchidei oraz przyjemną, owocową słodyczą, która balansuje delikatną, mineralną bazę. Herbata ta oferuje długie, eleganckie wykończenie i jest doskonałym przykładem rzemieślniczego podejścia do wydobywania nektarowych profili smakowych.'],
  ['superior-iron-goddess', 'To wysokiej klasy oolong z regionu Anxi, reprezentujący tradycyjny styl "średniego wypalenia", który nadaje mu głęboki i złożony charakter. Napar wyróżnia się idealnym balansem między świeżymi nutami kwiatów orchidei a bogatymi, maślanymi aromatami prażonych orzechów i karmelu. Herbata posiada gęstą, aksamitną teksturę i charakterystyczny dla tej odmiany długi, słodki posmak, który utrzymuje się na podniebieniu przez wiele parzeń.'],
  ['pear-cloud', 'To prestiżowy wysokogórski oolong z jednego z najwyżej położonych regionów upraw na Tajwanie - góry Li Shan (Góra Gruszy). Napar charakteryzuje się niezwykłą lekkością i krystaliczną czystością, oferując subtelne nuty kwiatów gruszy, świeżego ananasa oraz chłodnego, górskiego powietrza. Dzięki powolnemu wzrostowi krzewów w mglistym klimacie, herbata ta posiada gęstą, maślaną teksturę oraz długi, słodki posmak z wyraźnym mineralnym akcentem.'],
  ['catching-candy-clouds', 'To niezwykle rzadki, biały oolong z wysokogórskiego regionu Alishan na Tajwanie, zebrany z krzewów odmiany Qing Xin. Herbata ta przechodzi unikalny proces bardzo powolnego więdnięcia i minimalnej oksydacji, co skutkuje oszałamiającym aromatem waty cukrowej, pianek marshmallow i egzotycznych owoców. Napar jest lekki, eteryczny i krystalicznie czysty, oferując jedną z najbardziej deserowych i radosnych sesji herbacianych, jakie można sobie wyobrazić.'],
  ['2003-antique-nectar', 'To wyjątkowa, ponad 20-letnia herbata typu Sheng PuErh z regionu Yibang, która była przechowywana w optymalnych warunkach w Tajwanie. Napar charakteryzuje się niezwykłą, nektarową słodyczą oraz głębokim profilem z nutami suszonych owoców, antycznego drewna i miodu spadziowego. Herbata ta oferuje bardzo gładką, syropowatą teksturę oraz potężne, a jednocześnie kojące działanie energetyczne (Cha Qi), typowe dla wysokiej klasy dojrzałych herbat z drzew Gushu.'],
  ['nug-potion', 'To wyjątkowy, dojrzały Shu PuErh z 2024 roku, powstały wyłącznie z najmłodszych, złotych pąków herbacianych z regionu Menghai. Dzięki unikalnemu składowi napar jest niezwykle gęsty i kremowy, oferując intensywne nuty nugatu, mlecznej czekolady oraz prażonych orzechów laskowych. Herbata ta charakteryzuje się brakiem typowej dla tego gatunku ziemistości, dostarczając w zamian czystej, deserowej słodyczy i głębokiego poczucia relaksu.'],
  ['find-your-sunshine-3', 'To wyjątkowa edycja białej herbaty typu Shou Mei z 2024 roku, która została sprasowana w formę 7-gramowych kostek, idealnych do jednej sesji parzenia. Charakteryzuje się radosnym, słonecznym profilem z dominującymi nutami miodu wielokwiatowego, słodkich herbatników oraz suszonych moreli. Napar jest niezwykle przystępny i kojący, stanowiąc doskonały przykład naturalnej słodyczy, która z czasem będzie ewoluować w stronę głębszych, orzechowych aromatów.'],
  ['autumn-light', 'To biała herbata typu Shou Mei z jesiennego zbioru 2023 roku w regionie Fuding, która zachwyca swoją naturalną słodyczą i lekkością. Napar oferuje profil pełen nut miodu, suszonych jabłek oraz chrupiących jesiennych liści, z delikatnym kwiatowym tłem. Dzięki sprasowaniu w formę wygodnych kostek, herbata ta jest idealna do zabrania w podróż, zapewniając kojącą i ciepłą sesję w dowolnym miejscu.'],
  ['amulet-majesty', 'To prestiżowy, dojrzewający Shu PuErh w formie ciastka, stworzony z liści wiekowych drzew (Gushu) z regionu Jingmai w Yunnan. Charakteryzuje się niezwykle szlachetnym profilem z nutami antycznego drewna, słodkiej kamfory oraz głębokim, mineralnym tłem, które jest znakiem rozpoznawczym tego regionu. Napar posiada gęstą, jedwabistą teksturę i oferuje potężne, a zarazem kojące działanie energetyczne, typowe dla herbat najwyższej klasy.'],
  ['hunting-for-pralines', 'To wyjątkowa, rzemieślnicza herbata czarna (Hong Cha) z prowincji Yunnan, która swoją nazwę zawdzięcza niezwykle intensywnym, deserowym aromatom. Napar zachwyca bogatymi nutami ciemnej czekolady, palonego karmelu oraz prażonych orzechów laskowych, tworząc profil przypominający luksusowe praliny. Herbata charakteryzuje się gęstą, aksamitną teksturą i głęboką słodyczą, która pozostaje na podniebieniu długo po każdym łyku, nie wykazując przy tym żadnej goryczy.'],
  ['gateau-flapper', 'To wyjątkowa, rzemieślnicza herbata czarna (Hong Cha) z regionu Ningde w prowincji Fujian, wytwarzana z krzewów odmiany Jin Guanyin. Charakteryzuje się oszałamiającym profilem deserowym, w którym dominują nuty ciasta czekoladowego, konfitury malinowej oraz kremowej wanilii. Napar jest niezwykle gęsty i gładki, łącząc w sobie głęboką słodycz z delikatnym kwiatowym tłem, co czyni go idealnym wyborem dla miłośników bogatych, złożonych herbat o charakterze "gourmet".'],
  ['bright-heart-2021', 'To wyjątkowa, surowa herbata typu PuErh z regionu Jingmai, wytwarzana z liści wiekowych drzew (Gushu). Charakteryzuje się niezwykłą jasnością i czystością profilu, oferując intensywne nuty miodu, polnych kwiatów oraz świeżych moreli z charakterystycznym dla tego regionu mineralnym wykończeniem. Napar jest lekki, a jednocześnie posiada gęstą strukturę i długotrwały, słodki posmak, który z czasem będzie ewoluował w stronę głębszych, bardziej złożonych aromatów.'],
  ['genmai-matcha', 'To wyjątkowa japońska mieszanka łącząca w sobie trzy składniki: wysokiej jakości zieloną herbatę, prażony brązowy ryż oraz intensywną, ceremonialną matchę. Napar charakteryzuje się bogatym, "pocieszającym" profilem, w którym słodkie i orzechowe nuty prażonego ryżu są podbite głębokim, trawiastym umami matchy. Herbata ma żywy, neonowozielony kolor i gęstą teksturę, oferując sycące doznania przypominające połączenie świeżego naparu z aromatem ciepłego popcornu.'],
  ['souchong-liquor', 'To tradycyjna czarna herbata z regionu gór Wuyi, która w przeciwieństwie do powszechnych wersji rynkowych, nie jest aromatyzowana dymem, lecz poddawana naturalnemu procesowi utleniania. Charakteryzuje się niezwykle głębokim i słodkim profilem z wyraźnymi nutami suszonych longanów, ciemnej czekolady oraz melasy. Napar jest gęsty, gładki i posiada charakterystyczny dla tego gatunku „likierowy" posmak, który pozostaje na podniebieniu długo po degustacji.'],
  ['ruby-black', 'To słynna tajwańska herbata czarna z regionu Sun Moon Lake, powstała z unikalnej krzyżówki dzikiej herbaty z Tajwanu i odmiany Assam. Charakteryzuje się niezwykle intensywnym i rozpoznawalnym profilem smakowym z wyraźnymi nutami cynamonu, mięty oraz dojrzałych wiśni. Napar jest pełny, naturalnie słodki i posiada odświeżające, lekko mentolowe wykończenie, które wyróżnia tę herbatę na tle wszystkich innych czarnych herbat świata.'],
  ['lemon-blossom-frost', 'To wyjątkowa, rzemieślnicza herbata czarna (Hong Cha) z prowincji Yunnan, zbierana wczesną wiosną z krzewów odmiany Da Hao. Wyróżnia się niezwykle jasnym i świeżym profilem, łączącym nuty kwiatu cytryny, miodu akacjowego oraz skórki pomarańczowej z delikatnym, "mroźnym" mineralnym akcentem. Napar jest lekki, jedwabisty i pozbawiony goryczy, oferując unikalne połączenie głębi herbaty czarnej z rześkością wiosennego zbioru.'],
  ['wildwood-gold', 'To wyjątkowa, rzemieślnicza herbata czarna (Hong Cha) pochodząca z dziko rosnących drzew w regionie Feng Qing w prowincji Yunnan. Charakteryzuje się niezwykle bogatym profilem, w którym przeplatają się nuty ciemnego miodu leśnego, słodu oraz suszonych śliwek z wyraźnym mineralnym tłem. Napar posiada gęstą, niemal "oleistą" strukturę i oferuje potężne, rozgrzewające działanie, typowe dla herbat pozyskiwanych z dzikich, leśnych siedlisk.'],
  ['little-tong-mu', 'To wyjątkowa, rzemieślnicza herbata czarna (Hong Cha) z regionu Tong Mu, kolebki gatunku Lapsang Souchong, wytwarzana bez użycia dymu. Charakteryzuje się niezwykłą czystością i elegancją, oferując profil pełen nut słodkich ziemniaków, kakao oraz dojrzałych owoców longanu. Napar jest aksamitnie gładki, gęsty i posiada charakterystyczną mineralną bazę, która świadczy o wysokiej jakości surowca pochodzącego z chronionego rezerwatu przyrody.'],
  ['sultans-quill', 'To luksusowa, biała herbata typu Silver Needle (Yin Zhen) pochodząca z regionu Yunnan, wytwarzana wyłącznie z najmłodszych, pokrytych srebrzystym meszkiem pąków. Charakteryzuje się niezwykle delikatnym, a jednocześnie gęstym naparem o profilu smakowym przypominającym miód akacjowy, melona oraz świeże siano. Jest to herbata o wyjątkowej elegancji i czystości, oferująca subtelną słodycz i długi, jedwabisty posmak, który relaksuje i odświeża.'],
  ['ancient-haze', 'To wyjątkowa herbata biała typu Yue Guang Bai (Moonlight White) z 2024 roku, pochodząca z wiekowych drzew (Gushu) w regionie Jinggu. Charakteryzuje się niezwykle gęstym i syropowatym naparem o bogatych nutach miodu spadziowego, suszonych moreli oraz dojrzałego mango. Dzięki wysokiej jakości surowca z drzew gatunku Camellia Taliensis, herbata ta oferuje głębokie, relaksujące działanie cielesne i posiada ogromny potencjał do wieloletniego dojrzewania.'],
  ['midori-black', 'To unikalna japońska czarna herbata (Wakocha) z regionu Shizuoka, wytwarzana z kultywaru herbaty zielonej, co nadaje jej niezwykle oryginalny profil. W przeciwieństwie do ciężkich herbat czarnych, oferuje ona rześkie i owocowe nuty przypominające zielone jabłka, miód oraz delikatne aromaty kwiatowe. Napar jest lekki, naturalnie słodki i pozbawiony typowej dla czarnych herbat cierpkości, stanowiąc doskonały pomost między światem herbat zielonych i utlenionych.'],
  ['fig-butter-black', 'To wyjątkowa, rzemieślnicza czarna herbata z prowincji Yunnan, stworzona z wiosennych pąków i młodych liści odmiany Da Hao. Charakteryzuje się niezwykle gęstą, maślaną teksturą oraz deserowym profilem smakowym z wyraźnymi nutami suszonych fig, karmelu i słodu. Napar jest naturalnie słodki i aksamitny, oferując bogate doznania bez śladu goryczy, co czyni go idealnym wyborem dla osób szukających "treściwych" i kojących smaków.'],
  ['honeycomb-black', 'To rzemieślnicza czarna herbata z prowincji Yunnan, słynąca z niezwykle intensywnej, naturalnej słodyczy. Napar charakteryzuje się bogatymi nutami plastra miodu, ciemnego cukru oraz pieczonych owoców, z delikatnym akcentem kakao w tle. Herbata posiada gęstą, niemal syropowatą strukturę i oferuje głębokie, rozgrzewające doznania, które pozostają na podniebieniu w formie trwałego, miodowego posmaku.'],
  ['consorts-smile', 'To wyjątkowa, rzemieślnicza herbata czarna (Hong Cha) z prowincji Yunnan, zainspirowana owocem liczi, który według legendy był ulubionym przysmakiem cesarskiej konkubiny. Charakteryzuje się niezwykle intensywnym, owocowym profilem z wyraźnymi nutami właśnie liczi, róż oraz miodu kwiatowego. Napar jest niezwykle gładki i słodki, oferując eleganckie, niemal perfumeryjne doznania bez cienia goryczy.'],
  ['castleton-muscatel', 'Wyjątkowa herbata czarna z jednej z najbardziej prestiżowych posiadłości w indyjskim Darjeeling, zebrana podczas letniego zbioru (Second Flush). Słynie z charakterystycznego profilu „Muscatel", oferując wykwintne nuty dojrzałych winogron muszkatołowych, miodu oraz delikatne, kwiatowe tło. Napar jest lekki, elegancki i posiada szlachetną strukturę, która łączy w sobie rześkość z głęboką, owocową słodyczą.'],
  ['sweet-spice-jjm', 'To luksusowa herbata czarna z gór Wuyi, wytwarzana wyłącznie z najmłodszych, maleńkich pąków herbacianych. Charakteryzuje się niezwykle złożonym profilem, w którym słodycz miodu i kakao łączy się z subtelnymi nutami korzennymi oraz aromatem pieczonych batatów. Napar jest aksamitnie gładki, gęsty i oferuje długie, eleganckie wykończenie, będąc jednym z najbardziej cenionych przykładów nowoczesnego rzemiosła produkcji herbat czarnych w Chinach.'],
  ['wild-resin-lapsang', 'To wyjątkowa, rzemieślnicza herbata czarna (Hong Cha) z regionu Tong Mu, kolebki gatunku Lapsang Souchong, wytwarzana z liści dziko rosnących krzewów. Wyróżnia się niezwykle czystym i intensywnym profilem, w którym słodycz dojrzałych owoców łączy się z głębokimi, leśnymi nutami żywicy sosnowej oraz miodu spadziowego. Napar jest aksamitnie gładki, pozbawiony dymnego aromatu typowego dla wersji eksportowych, oferując w zamian szlachetną mineralność i trwałą, nektarową słodycz.'],
  ['golden-bud', 'To luksusowa herbata czarna z prowincji Yunnan, składająca się wyłącznie z młodych, puszystych pąków, które po utlenieniu zyskują intensywnie złoty kolor. Charakteryzuje się niezwykle gładką, niemal kremową teksturą oraz bogatym profilem smakowym z dominującymi nutami słodu, ciemnego miodu i kakao. Napar jest naturalnie słodki, pozbawiony goryczy i oferuje głębokie, rozgrzewające doznania z trwałym, karmelowym posmakiem.'],
  ['chamomile-flowers', 'To wysokiej jakości napar ziołowy składający się z całych, wysuszonych kwiatów rumianku pospolitego. Charakteryzuje się niezwykle czystym, słodkim smakiem z wyraźnymi nutami jabłek i miodu, bez goryczy często spotykanej w produktach gorszej jakości. Napar działa kojąco i relaksująco, będąc idealnym wyborem na wieczorne wyciszenie organizmu przed snem.'],
  ['amachazuru', 'To naturalnie słodki napar ziołowy, znany również jako "Jiaogulan" lub "zioło nieśmiertelności", zbierany z dziko rosnących pnączy w Chinach. Charakteryzuje się unikalnym profilem smakowym łączącym nuty lukrecji, świeżego ogórka i słodkiej stewii, pozostawiając na podniebieniu trwały, odświeżający posmak. Napar ten jest ceniony w tradycyjnej medycynie za swoje właściwości adaptogenne i prozdrowotne, a ponieważ naturalnie nie zawiera kofeiny, jest doskonałym wyborem o każdej porze dnia.'],
  ['butterfly-pea', 'To niezwykły napar ziołowy z całych kwiatów klitorii, który słynie z głębokiego, kobaltowego koloru oraz zdolności do zmiany barwy na fioletową po dodaniu soku z cytryny. Posiada bardzo łagodny, lekko drzewny i ziemisty profil smakowy, przypominający nieco młodą zieloną herbatę. Napar jest wolny od kofeiny, bogaty w antyoksydanty i stanowi spektakularną bazę do kolorowych napojów oraz koktajli.'],
  ['purple-rose', 'To wyjątkowy napar ziołowy składający się z młodych, suszonych pąków dzikiej róży o głębokim, purpurowym kolorze. Charakteryzuje się niezwykle intensywnym, kwiatowym aromatem oraz delikatnym, naturalnie słodkim smakiem z subtelną owocową kwasowością. Napar jest wolny od kofeiny i bogaty w witaminy, oferując eleganckie i kojące doświadczenie, które świetnie sprawdza się zarówno solo, jak i jako dodatek do herbat.'],
  ['chrysanthemum', 'To wysokiej jakości napar ziołowy składający się z całych kwiatów chryzantemy odmiany Gong Ju (Chryzantema Cesarska) z gór Huangshan. Charakteryzuje się niezwykle czystym, słodkim i lekko maślanym profilem z wyraźnymi nutami miodu oraz białych kwiatów. Napar jest ceniony w tradycyjnej medycynie chińskiej za swoje właściwości chłodzące i odświeżające, a ponieważ nie zawiera kofeiny, jest idealnym wyborem na każdą porę dnia.'],
  ['rooibos', 'To wysokiej jakości napar z południowoafrykańskiego czerwonokrzewu, charakteryzujący się głębokim, rubinowym kolorem i naturalnie słodkim profilem. W smaku dominują bogate nuty wanilii, miodu oraz delikatna drzewna baza, które tworzą kojącą i pełną strukturę bez śladu goryczy. Napar jest całkowicie wolny od kofeiny i bogaty w minerały, dzięki czemu stanowi idealny, relaksujący napój dla całej rodziny o każdej porze dnia.'],
  ['lemon-verbena', 'To wyjątkowo aromatyczny napar ziołowy z całych liści werbeny, zbieranych w szczycie sezonu dla zachowania pełni olejków eterycznych. Charakteryzuje się intensywnym, orzeźwiającym smakiem czystej cytryny z delikatnym, słodko-ziołowym tłem, przypominającym sorbet cytrynowy. Napar jest wolny od kofeiny, działa kojąco na układ trawienny i jest idealnym wyborem zarówno na gorąco, jak i w formie mrożonej herbaty.'],
  ['hibiscus-flowers', 'To wysokiej jakości napar z całych, wysuszonych kwiatów hibiskusa, który po zaparzeniu daje intensywnie rubinowy kolor. Charakteryzuje się wyrazistym, kwaskowatym profilem z nutami żurawiny, czerwonych porzeczek i owoców dzikiej róży. Napar jest naturalnie wolny od kofeiny, bogaty w witaminę C i świetnie sprawdza się zarówno jako rozgrzewający napój, jak i baza do orzeźwiających herbat mrożonych.'],
  ['peppermint-leaf', 'To wyjątkowo aromatyczny napar z całych, starannie wyselekcjonowanych liści mięty pieprzowej, charakteryzujący się wysoką zawartością olejków eterycznych. Oferuje niezwykle czysty i intensywny profil smakowy z dominującym, chłodzącym mentolem oraz naturalną słodyczą, która pozostawia na podniebieniu długotrwałe uczucie świeżości. Napar jest wolny od kofeiny i doskonale wspomaga trawienie, będąc klasycznym wyborem na każdą porę dnia.'],
  ['dandelion-leaf', 'To naturalny napar ziołowy o łagodnym, "zielonym" profilu, który przypomina połączenie delikatnej herbaty liściastej z nutami słodkiej kukurydzy i świeżych ziół. Liście mniszka są cenione za swoje właściwości oczyszczające i wspomagające trawienie, oferując czysty, lekko ziemisty smak bez nadmiernej goryczy. Jest to napar całkowicie wolny od kofeiny, idealny dla osób szukających naturalnego wsparcia dla organizmu w codziennej diecie.'],
  ['ginkgo-leaf-tips', 'To wysokiej jakości napar z młodych pędów miłorzębu, zbieranych ręcznie w celu zachowania maksymalnej świeżości i właściwości. Charakteryzuje się łagodnym, roślinnym profilem z subtelnymi nutami słodkich orzechów i zboża, przypominającym niektóre rodzaje lekkich zielonych herbat. Napar jest ceniony za swoje właściwości wspomagające koncentrację i krążenie, a ponieważ nie zawiera kofeiny, stanowi doskonałe uzupełnienie codziennej rutyny dbającej o sprawność umysłową.'],
  ['rose-buds', 'To wyjątkowo aromatyczny napar ziołowy składający się z młodych, całych pąków róż, zbieranych tuż przed rozkwitem, aby zachować ich delikatność. Charakteryzuje się subtelnym, naturalnie słodkim smakiem oraz kojącym zapachem, który przywodzi na myśl kwitnący letni ogród. Napar jest wolny od kofeiny i bogaty w antyoksydanty, stanowiąc elegancki dodatek do mieszanek herbacianych lub relaksujący napój pity samodzielnie.'],
]);

const slugAliases = {
  'amachazuru-five-leaf': 'amachazuru',
  'butterfly-pea-flower': 'butterfly-pea',
  'chrysanthemum-flowers': 'chrysanthemum',
  'castleton-muscatel-special-reserve-lot': 'castleton-muscatel',
  'duck-sh-t-oolong': 'duck-shit-oolong',
};

function toTeaSlug(name) {
  return name
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[’']/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

async function main() {
  // Wipe demo tables and reset all auto-increment sequences
  await prisma.$executeRawUnsafe(
    'TRUNCATE TABLE "brewing_instructions", "Tea", "brewing_style", "tea_category" RESTART IDENTITY CASCADE',
  );

  const iconColumnCheck = await prisma.$queryRawUnsafe(
    `
      SELECT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'tea_category'
          AND column_name = 'icon_url'
      ) AS "exists"
    `,
  );
  const hasCategoryIconColumn = Boolean(iconColumnCheck?.[0]?.exists);

  const categorySeeds = [
    { name: 'White', icon_url: 'https://img.icons8.com/?size=100&id=rCUgZeMLbaAM&format=png&color=C8A96A' },
    { name: 'Yellow', icon_url: 'https://img.icons8.com/?size=100&id=rCUgZeMLbaAM&format=png&color=E8B233' },
    { name: 'Raw Puerh', icon_url: 'https://img.icons8.com/?size=100&id=rCUgZeMLbaAM&format=png&color=8A4B2A' },
    { name: 'Green', icon_url: 'https://img.icons8.com/?size=100&id=rCUgZeMLbaAM&format=png&color=4D8B31' },
    { name: 'Oolong', icon_url: 'https://img.icons8.com/?size=100&id=rCUgZeMLbaAM&format=png&color=C9792B' },
    { name: 'Ripened', icon_url: 'https://img.icons8.com/?size=100&id=rCUgZeMLbaAM&format=png&color=6B3F2A' },
    { name: 'Matcha', icon_url: 'https://img.icons8.com/?size=100&id=rCUgZeMLbaAM&format=png&color=5FA641' },
    { name: 'Black', icon_url: 'https://img.icons8.com/?size=100&id=rCUgZeMLbaAM&format=png&color=2F2A25' },
    { name: 'Tisanes', icon_url: 'https://img.icons8.com/?size=100&id=rCUgZeMLbaAM&format=png&color=B85E7A' },
  ];

  // 1. Create categories
  let categories;
  if (hasCategoryIconColumn) {
    categories = await Promise.all(
      categorySeeds.map((category) => prisma.tea_category.create({ data: category })),
    );
  } else {
    for (const category of categorySeeds) {
      await prisma.$executeRawUnsafe(
        `INSERT INTO "tea_category" ("name") VALUES ('${category.name.replace(/'/g, "''")}')`,
      );
    }

    categories = await prisma.$queryRawUnsafe(
      'SELECT "id", "name" FROM "tea_category" ORDER BY "id" ASC',
    );
  }

  const [whiteCategory, yellowCategory, rawPuerhCategory, greenCategory, oolongCategory, ripenedCategory, matchaCategory, blackCategory, tisanesCategory] = categories;

  // 2. Create brewing styles
  const [gongfuStyle, westernStyle] = await Promise.all([
    prisma.brewing_style.create({ data: { name: 'Gongfu', description: 'High leaf ratio and short steeps in many infusions.' } }),
    prisma.brewing_style.create({ data: { name: 'Western', description: 'Lower leaf ratio and longer steeps.' } }),
  ]);

  // 3. Define all teas
  const allTeas = [
    // --- WHITE TEAS ---
    { name: 'Heirloom Silver Needle', brew_temp: 95, categoryId: whiteCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 30, increment_seconds: 5, max_infusions: 7 }, western: { grams_per_100ml: 0.6, first_infusion_seconds: 180, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Silver Needle', brew_temp: 90, categoryId: whiteCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 45, increment_seconds: 10, max_infusions: 5 }, western: { grams_per_100ml: 0.7, first_infusion_seconds: 180, increment_seconds: 30, max_infusions: 3 } },
    { name: 'White Peony', brew_temp: 95, categoryId: whiteCategory.id, gongFu: { grams_per_100ml: 3.5, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 7 }, western: { grams_per_100ml: 0.6, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Moonlight White', brew_temp: 99, categoryId: whiteCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 30, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 0.7, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Wild Slumber', brew_temp: 99, categoryId: whiteCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 12 }, western: { grams_per_100ml: 0.6, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },
    { name: 'Simple Dreams 3', brew_temp: 99, categoryId: whiteCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 15 }, western: { grams_per_100ml: 0.6, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },
    { name: 'Jade Star 9', brew_temp: 99, categoryId: whiteCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 15 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },
    { name: 'Lost Origin White', brew_temp: 95, categoryId: whiteCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 30, increment_seconds: 5, max_infusions: 7 }, western: { grams_per_100ml: 0.6, first_infusion_seconds: 180, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Purple Bud', brew_temp: 90, categoryId: whiteCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 30, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 0.7, first_infusion_seconds: 240, increment_seconds: 60, max_infusions: 2 } },

    // --- YELLOW TEAS ---
    { name: 'Wenzhou Gold', brew_temp: 80, categoryId: yellowCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 45, increment_seconds: 10, max_infusions: 5 }, western: { grams_per_100ml: 0.7, first_infusion_seconds: 240, increment_seconds: 60, max_infusions: 2 } },
    { name: 'Amber Mountain', brew_temp: 75, categoryId: yellowCategory.id, gongFu: { grams_per_100ml: 3.5, first_infusion_seconds: 60, increment_seconds: 10, max_infusions: 5 }, western: { grams_per_100ml: 0.6, first_infusion_seconds: 120, increment_seconds: 60, max_infusions: 3 } },
    { name: 'Sovereign Bud', brew_temp: 80, categoryId: yellowCategory.id, gongFu: { grams_per_100ml: 3.5, first_infusion_seconds: 60, increment_seconds: 10, max_infusions: 5 }, western: { grams_per_100ml: 0.6, first_infusion_seconds: 240, increment_seconds: 60, max_infusions: 2 } },
    { name: 'Diamond Peak', brew_temp: 75, categoryId: yellowCategory.id, gongFu: { grams_per_100ml: 3.5, first_infusion_seconds: 120, increment_seconds: 15, max_infusions: 5 }, western: { grams_per_100ml: 0.6, first_infusion_seconds: 240, increment_seconds: 60, max_infusions: 2 } },

    // --- RAW PUERH ---
    { name: 'Legend Of The Limelight', brew_temp: 95, categoryId: rawPuerhCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 15 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },
    { name: 'Young Gushu 2025', brew_temp: 95, categoryId: rawPuerhCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 12 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: "90's Enigma Sheng", brew_temp: 99, categoryId: rawPuerhCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 15 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Glam Countess', brew_temp: 95, categoryId: rawPuerhCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 12 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },
    { name: 'Midnight Oracle', brew_temp: 95, categoryId: rawPuerhCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 12 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },
    { name: 'Bliss Beholder', brew_temp: 95, categoryId: rawPuerhCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 12 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },
    { name: 'Off The Apps', brew_temp: 99, categoryId: rawPuerhCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 10 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Sweet Treat Envoy', brew_temp: 95, categoryId: rawPuerhCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 12 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },
    { name: 'Juice Journo', brew_temp: 99, categoryId: rawPuerhCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 30, increment_seconds: 5, max_infusions: 12 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },

    // --- GREEN TEAS ---
    { name: 'Dragon Pearl Jasmine', brew_temp: 80, categoryId: greenCategory.id, gongFu: { grams_per_100ml: 6.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 5 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 180, increment_seconds: 60, max_infusions: 2 } },
    { name: 'Cloud Lake', brew_temp: 80, categoryId: greenCategory.id, gongFu: { grams_per_100ml: 3.5, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 7 }, western: { grams_per_100ml: 0.6, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Kabuse Saeakari', brew_temp: 70, categoryId: greenCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 60, increment_seconds: 10, max_infusions: 4 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Monkey Picked', brew_temp: 85, categoryId: greenCategory.id, gongFu: { grams_per_100ml: 2.0, first_infusion_seconds: 90, increment_seconds: 20, max_infusions: 5 }, western: { grams_per_100ml: 0.3, first_infusion_seconds: 180, increment_seconds: 60, max_infusions: 2 } },
    { name: 'Tianshan Mist', brew_temp: 80, categoryId: greenCategory.id, gongFu: { grams_per_100ml: 3.5, first_infusion_seconds: 30, increment_seconds: 10, max_infusions: 6 }, western: { grams_per_100ml: 0.6, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Jade Arrow - Pre Qing Ming', brew_temp: 85, categoryId: greenCategory.id, gongFu: { grams_per_100ml: 3.0, first_infusion_seconds: 30, increment_seconds: 5, max_infusions: 5 }, western: { grams_per_100ml: 0.5, first_infusion_seconds: 180, increment_seconds: 60, max_infusions: 2 } },
    { name: 'Fur Peak Supreme', brew_temp: 80, categoryId: greenCategory.id, gongFu: { grams_per_100ml: 3.0, first_infusion_seconds: 45, increment_seconds: 5, max_infusions: 5 }, western: { grams_per_100ml: 0.5, first_infusion_seconds: 180, increment_seconds: 60, max_infusions: 2 } },

    // --- OOLONG TEAS ---
    { name: 'Amber Gaba Oolong', brew_temp: 99, categoryId: oolongCategory.id, gongFu: { grams_per_100ml: 6.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 9 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Butterscotch Temple', brew_temp: 99, categoryId: oolongCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 10, max_infusions: 9 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Yunnan Beauty', brew_temp: 95, categoryId: oolongCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 9 }, western: { grams_per_100ml: 0.6, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Tiger Eye Gaba', brew_temp: 99, categoryId: oolongCategory.id, gongFu: { grams_per_100ml: 6.0, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 10 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },
    { name: 'Duck Sh*t Oolong', brew_temp: 95, categoryId: oolongCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 9 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Alishan Creams', brew_temp: 95, categoryId: oolongCategory.id, gongFu: { grams_per_100ml: 6.0, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 9 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Lotus Peak Rou Gui', brew_temp: 99, categoryId: oolongCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 10 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Stone Milk', brew_temp: 99, categoryId: oolongCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 30, increment_seconds: 5, max_infusions: 10 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Honey Duchess', brew_temp: 95, categoryId: oolongCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Royal Peach Orchid', brew_temp: 95, categoryId: oolongCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 9 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Superior Iron Goddess', brew_temp: 95, categoryId: oolongCategory.id, gongFu: { grams_per_100ml: 6.0, first_infusion_seconds: 15, increment_seconds: 10, max_infusions: 9 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Pear Cloud', brew_temp: 95, categoryId: oolongCategory.id, gongFu: { grams_per_100ml: 6.0, first_infusion_seconds: 30, increment_seconds: 5, max_infusions: 12 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },

    // --- RIPENED / DARK TEAS ---
    { name: 'Catching Candy Clouds', brew_temp: 99, categoryId: ripenedCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 15 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: '2003 Antique Nectar', brew_temp: 99, categoryId: ripenedCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 15 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Nug Potion', brew_temp: 99, categoryId: ripenedCategory.id, gongFu: { grams_per_100ml: 6.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 25 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 7 } },
    { name: 'Find Your Sunshine 3', brew_temp: 99, categoryId: ripenedCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 15 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },
    { name: 'Autumn Light', brew_temp: 99, categoryId: ripenedCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 10, increment_seconds: 5, max_infusions: 15 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },
    { name: 'Amulet Majesty', brew_temp: 99, categoryId: ripenedCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 15, increment_seconds: 5, max_infusions: 12 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },
    { name: 'Hunting For Pralines', brew_temp: 99, categoryId: ripenedCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 15 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Gateau Flapper', brew_temp: 99, categoryId: ripenedCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 15 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Bright Heart 2021', brew_temp: 99, categoryId: ripenedCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 12 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 5 } },

    // --- MATCHA ---
    { name: 'Genmai Matcha', brew_temp: 80, categoryId: matchaCategory.id, gongFu: { grams_per_100ml: 6.0, first_infusion_seconds: 15, increment_seconds: 10, max_infusions: 5 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },

    // --- BLACK TEAS ---
    { name: 'Souchong Liquor', brew_temp: 90, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 15, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 0.6, first_infusion_seconds: 120, increment_seconds: 60, max_infusions: 3 } },
    { name: 'Ruby Black', brew_temp: 95, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 4.5, first_infusion_seconds: 15, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 60, max_infusions: 4 } },
    { name: 'Lemon Blossom Frost', brew_temp: 90, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 30, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 1.0, first_infusion_seconds: 120, increment_seconds: 60, max_infusions: 2 } },
    { name: 'Wildwood Gold', brew_temp: 95, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 7 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 60, max_infusions: 2 } },
    { name: 'Little Tong Mu', brew_temp: 95, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 4.5, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 90, increment_seconds: 30, max_infusions: 3 } },
    { name: "Sultan's Quill", brew_temp: 95, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 10 }, western: { grams_per_100ml: 0.7, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Ancient Haze', brew_temp: 95, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 20, increment_seconds: 10, max_infusions: 7 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Midori Black', brew_temp: 90, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 7 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Fig Butter Black', brew_temp: 95, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Honeycomb Black', brew_temp: 95, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 0.7, first_infusion_seconds: 120, increment_seconds: 60, max_infusions: 2 } },
    { name: "Consort's Smile", brew_temp: 95, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 4.5, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Castleton Muscatel - Special Reserve Lot', brew_temp: 90, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 3.5, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 1.6, first_infusion_seconds: 300, increment_seconds: 100, max_infusions: 2 } },
    { name: 'Sweet Spice JJM', brew_temp: 95, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 25, increment_seconds: 5, max_infusions: 7 }, western: { grams_per_100ml: 0.7, first_infusion_seconds: 120, increment_seconds: 60, max_infusions: 3 } },
    { name: 'Wild Resin Lapsang', brew_temp: 95, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 5.0, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 3 } },
    { name: 'Golden Bud', brew_temp: 95, categoryId: blackCategory.id, gongFu: { grams_per_100ml: 4.0, first_infusion_seconds: 20, increment_seconds: 5, max_infusions: 8 }, western: { grams_per_100ml: 0.8, first_infusion_seconds: 120, increment_seconds: 60, max_infusions: 3 } },

    // --- TISANES (HERBAL) ---
    { name: 'Chamomile Flowers', brew_temp: 99, categoryId: tisanesCategory.id, gongFu: { grams_per_100ml: 1.5, first_infusion_seconds: 30, increment_seconds: 15, max_infusions: 5 }, western: { grams_per_100ml: 0.3, first_infusion_seconds: 120, increment_seconds: 60, max_infusions: 2 } },
    { name: 'Amachazuru Five Leaf', brew_temp: 99, categoryId: tisanesCategory.id, gongFu: { grams_per_100ml: 2.0, first_infusion_seconds: 30, increment_seconds: 15, max_infusions: 5 }, western: { grams_per_100ml: 0.3, first_infusion_seconds: 120, increment_seconds: 60, max_infusions: 2 } },
    { name: 'Butterfly Pea Flower', brew_temp: 99, categoryId: tisanesCategory.id, gongFu: { grams_per_100ml: 2.5, first_infusion_seconds: 30, increment_seconds: 20, max_infusions: 3 }, western: { grams_per_100ml: 0.4, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Purple Rose', brew_temp: 99, categoryId: tisanesCategory.id, gongFu: { grams_per_100ml: 3.0, first_infusion_seconds: 25, increment_seconds: 10, max_infusions: 5 }, western: { grams_per_100ml: 0.5, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Chrysanthemum Flowers', brew_temp: 99, categoryId: tisanesCategory.id, gongFu: { grams_per_100ml: 1.5, first_infusion_seconds: 15, increment_seconds: 5, max_infusions: 5 }, western: { grams_per_100ml: 0.3, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Rooibos', brew_temp: 99, categoryId: tisanesCategory.id, gongFu: { grams_per_100ml: 2.0, first_infusion_seconds: 30, increment_seconds: 15, max_infusions: 5 }, western: { grams_per_100ml: 0.3, first_infusion_seconds: 120, increment_seconds: 60, max_infusions: 2 } },
    { name: 'Lemon Verbena', brew_temp: 99, categoryId: tisanesCategory.id, gongFu: { grams_per_100ml: 1.5, first_infusion_seconds: 15, increment_seconds: 5, max_infusions: 5 }, western: { grams_per_100ml: 0.3, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Hibiscus Flowers', brew_temp: 99, categoryId: tisanesCategory.id, gongFu: { grams_per_100ml: 2.0, first_infusion_seconds: 15, increment_seconds: 5, max_infusions: 5 }, western: { grams_per_100ml: 0.3, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Peppermint Leaf', brew_temp: 99, categoryId: tisanesCategory.id, gongFu: { grams_per_100ml: 1.5, first_infusion_seconds: 15, increment_seconds: 5, max_infusions: 5 }, western: { grams_per_100ml: 0.3, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Dandelion Leaf', brew_temp: 99, categoryId: tisanesCategory.id, gongFu: { grams_per_100ml: 1.5, first_infusion_seconds: 15, increment_seconds: 5, max_infusions: 5 }, western: { grams_per_100ml: 0.3, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Ginkgo Leaf Tips', brew_temp: 99, categoryId: tisanesCategory.id, gongFu: { grams_per_100ml: 1.5, first_infusion_seconds: 15, increment_seconds: 5, max_infusions: 5 }, western: { grams_per_100ml: 0.3, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
    { name: 'Rose Buds', brew_temp: 99, categoryId: tisanesCategory.id, gongFu: { grams_per_100ml: 3.0, first_infusion_seconds: 15, increment_seconds: 5, max_infusions: 5 }, western: { grams_per_100ml: 0.5, first_infusion_seconds: 120, increment_seconds: 30, max_infusions: 2 } },
  ];

  // 4. Add all teas to database
  console.log(`Starting to add ${allTeas.length} teas...`);
  for (const tea of allTeas) {
    const normalizedSlug = toTeaSlug(tea.name);
    const descriptionSlug = slugAliases[normalizedSlug] || normalizedSlug;

    const createdTea = await prisma.tea.create({
      data: {
        name: tea.name,
        description: teaDescriptions.get(descriptionSlug) || null,
        categoryId: tea.categoryId,
        brew_temp: tea.brew_temp,
      },
    });

    // Add brewing instructions
    await prisma.brewing_instructions.createMany({
      data: [
        {
          teaId: createdTea.id,
          styleId: gongfuStyle.id,
          grams_per_100ml: tea.gongFu.grams_per_100ml,
          first_infusion_seconds: tea.gongFu.first_infusion_seconds,
          increment_seconds: tea.gongFu.increment_seconds,
          max_infusions: tea.gongFu.max_infusions,
        },
        {
          teaId: createdTea.id,
          styleId: westernStyle.id,
          grams_per_100ml: tea.western.grams_per_100ml,
          first_infusion_seconds: tea.western.first_infusion_seconds,
          increment_seconds: tea.western.increment_seconds,
          max_infusions: tea.western.max_infusions,
        },
      ],
    });
  }

  const teaCount = await prisma.tea.count();
  console.log(`\n Seed completed. Teas in database: ${teaCount}`);
}

main()
  .catch((error) => {
    console.error('Seed error:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
