apiVersion: v1
kind: Secret
metadata:
  name: iotea-secrets
stringData:
  POSTGRES_USER: iotea_user
  POSTGRES_PASSWORD: iotea_pass
  POSTGRES_DB: iotea
  DATABASE_URL: postgresql://iotea_user:iotea_pass@postgres:5432/iotea
  REDIS_URL: redis://redis:6379
  MQTT_URL: mqtt://emqx:1883
  EMQX_COOKIE: iotea_emqx_cluster_cookie
