apiVersion: v1
kind: Secret
metadata:
  name: iotea-secrets
stringData:
  POSTGRES_USER: iotea_user
  POSTGRES_PASSWORD: CHANGE_ME
  POSTGRES_DB: iotea
  DATABASE_URL: postgresql://iotea_user:CHANGE_ME@postgres:5432/iotea
  REDIS_URL: redis://redis:6379
  MQTT_URL: mqtt://emqx:1883
  EMQX_COOKIE: CHANGE_ME
  JWT_SECRET: CHANGE_ME
  MQTT_API_URL: http://emqx:18083/api/v5
  MQTT_API_KEY: CHANGE_ME
  MQTT_API_SECRET: CHANGE_ME
  MQTT_WORKER_USERNAME: mqtt_worker
  MQTT_WORKER_PASSWORD: CHANGE_ME
  MQTT_API_USERNAME: mqtt_api_user
  MQTT_API_PASSWORD: CHANGE_ME
  FIREBASE_PROJECT_ID: CHANGE_ME
  FIREBASE_CLIENT_EMAIL: CHANGE_ME@CHANGE_ME.iam.gserviceaccount.com
  FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nCHANGE_ME\n-----END PRIVATE KEY-----\n"
